### ISSUE TITLE
ref=* tags on links

### ISSUE THREAD

**Issue by mihaii-telenav** [TelenavMapping/US_mapping_projects#25]
During our editing process, we encounter various situations where ref tags are present on links.

Looking at the [motorway_link OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_link):

![image](https://user-images.githubusercontent.com/20751382/44568477-9f4b5680-a77f-11e8-8e1a-ca7a12b0b67d.png)
So the ref tag is accepted and recommended to be used.

On the other hand, the general [highway link OSM wiki](https://wiki.openstreetmap.org/wiki/Highway_link) says that very few link roads have on them route refs:

![image](https://user-images.githubusercontent.com/20751382/44568614-3ca68a80-a780-11e8-81bb-b297f2053ecd.png)

Below are a couple of examples with link roads that have refs:

- [way 60178013](https://www.openstreetmap.org/way/60178013) @ 42.251034, -88.146945

- [way 15191231](https://www.openstreetmap.org/way/15191231) @ 29.7018493, -98.0962244

- [way 14987288](https://www.openstreetmap.org/way/14987288) @ 35.3846081, -97.0879561

- [way 180527913](https://www.openstreetmap.org/way/180527913) @ 35.0158628, -106.0694184

All of the above links are included in a route relation, which have the ref tag included in the relation.

So, what's the general consensus regarding this topic? Should the ref=* tag be added on the links? Should it be removed when encountering such a situation if the link is in a route relation that already has the ref=* tag in it?

**Comment by jleedev** [comment]
It looks like the wiki is merely trying to say that when a link has a ref, it is the ref of the _route_ it carries, and not an exit number. Similarly, tagging a link with the name of the _exit_ is not the right place for it. It's almost paradoxical for a link to have a name — the named road would continue as a regular highway.

Based on looking at some data (in the US), named links are either a mistake (an attempt to name the junction) or a judgment call as to what's a link and what's the road proper, which is mostly correct but could conceivably be tidied up a bit. Ref'd links are usually correct.

To me this looks exactly the same as "refs on highways" — they should be replaced by route relations, but that's not happening anytime soon.

**Comment by mihaii-telenav** [comment]
We've received quite a number of [replies](https://lists.openstreetmap.org/pipermail/talk-us/2018-August/018797.html) on the mailing list, but we couldn't draw a clear conclusion based on this. From now on, we will approach these situations as follows:

- When encountering cases where the link **is _not_ part** of a road route relation, we will **_delete_** the ref=* tag.
- When encountering cases where the links **is part** of a road route relation, we will **_keep_** the ref=* tag on link.

If community members from a certain city complain about this approach, we will follow the local rules regarding this topic.
